### ISSUE TITLE
Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by HelloDeadline** [nidu/vscode-copy-json-path#1]
Linux Mint v17
VSCode v1.12.2

Tested in valid json, tried multiple cursor positions.

**Comment by nidu** [comment]
Hello. Do you see message "Couldn't copy path" or "Invalid JSON"? Could you please provide VSCode logs after doing this action? Did you try to run the action on the same file on some other OS?

**Comment by enviable** [comment]
This uses https://github.com/xavi-/node-copy-paste which requires xclip to be installed.
If you install xclip, it works.
