### ISSUE TITLE
How to configure to use quotes

### ISSUE THREAD

**Issue by canklot** [nidu/vscode-copy-json-path#13]
Hi thanks for the extension. I couldn't make it work for the quotes. What should I write in `Copy JSON Path: Non Quoted Key Regex` field to use quotes?

I want this
`json_data["entry"][0]["changes"][0]["value"]`

Instead of this
`json_data.entry[0].changes[0].value`

**Comment by nidu** [comment]
Hi @canklot.

`Copy JSON Path: Non Quoted Key Regex` defines regex that is used to test whether the key must be quoted. If you want all your parts to be quoted - use regex that doesn't match anything. Simple one for JSON would be just a single space ` `, which will work unless you don't have map keys consisting of just a single space. To be safer you can also use `a{1000}` for example, which will work unless you have a key consisting of 1000 a letters.

As for `json_data` - this is going to be presented as `["json_data"]` as well. If you want to not escape the first part only - that's not generally supported as regex is not aware of part index. If you find you work a lot with objects having `json_data` key as the first part - you can set up your non quoted key regex to `json_data`.

**Comment by canklot** [comment]
> Copy JSON Path: Non Quoted Key Regex

Single space worked thanks 👍

Maybe include this information in readme. And `json_data` is just my variable no need for any fancy regex 🙂

**Comment by nidu** [comment]
Added in version 0.2.1, thanks!
