### ISSUE TITLE
Does not work in debian

### ISSUE THREAD

**Issue by degacth** [nidu/vscode-copy-json-path#2]

**Comment by nidu** [comment]
What version of Debian and VS Code do you use?
And could you also post JSON (or minimal code fragment to reproduce the error) and cursor position where error occurs. Maybe it has nothing to do with Debian.

**Comment by enviable** [comment]
This uses https://github.com/xavi-/node-copy-paste which requires xclip to be installed.
If you install xclip, it works.

**Comment by amoshydra** [comment]
I cound't use this extension inside Remote WSL and Remove Container environment. https://github.com/xavi-/node-copy-paste doesn't seems to work in these environments. Installing xclip doesn't help either.

I have created a PR https://github.com/nidu/vscode-copy-json-path/pull/8 to replace `node-copy-paste` with VS Code clipboard API instead.
