### ISSUE TITLE
YAML support?

### ISSUE THREAD

**Issue by rattrayalex** [nidu/vscode-copy-json-path#20]
Hi, would you consider adding yaml support? I actually think this maybe used to work, perhaps on accident, but I could be hallucinating.

Related: https://github.com/redhat-developer/vscode-yaml/issues/999

**Comment by nidu** [comment]
Hi, there's some progress JSON parsing, so it could work accidentally with a particular shape of YAML. I think YAML is much more complicated and adding YAML support conflicts with the extension name, so maybe adding a separate similar extension would make more sense.
