### ISSUE TITLE
Setting to change delimiter from `.` to any character

### ISSUE THREAD

**Issue by andymerskin** [nidu/vscode-copy-json-path#21]
This extension has been a godsend for copying JSON paths from translations files for i18n, however in our project's configuration, we use colons `:` to delimit between path elements instead of `.` by default.

It would be amazing if this were configurable to accept any character rather that period `.`

**Comment by nidu** [comment]
@andymerskin added `pathSeparator` option with `.` as default

**Comment by andymerskin** [comment]
@nidu You are a hero, thanks!
