### ISSUE TITLE
Make JSONtoPath a npm lib

### ISSUE THREAD

**Issue by Xterionix** [nidu/vscode-copy-json-path#22]
I've been trying to figure out a good way to get the JSON path from the cursor position and this does it really well.
I was hoping if this was made into an npm package then I'd be able to use it.
I'm open to helping set it up if that's a concern.

**Comment by nidu** [comment]
Hi, there's a dependency on acorn, because it works with JS as well. If you're working with pure JSON - it might be done in a more lightweight (maybe more performant) manner and without a dedicated JS parser. Unless size is a concern.
