### ISSUE TITLE
Copy object path?

### ISSUE THREAD

**Issue by simkessy** [nidu/vscode-copy-json-path#4]
Could you get it to copy the path within a js object?

**Comment by nidu** [comment]
Hello, published new version with basic JS support, you can try it. Let me know if find any bugs.

**Comment by nidu** [comment]
It doesn't work inside functions or blocks wrapped with curly braces so unusable at the moment. Didn't make right tests.

**Comment by nidu** [comment]
It should work now in v0.0.5. Acorn is used for parsing so it expects valid JS.
