### ISSUE TITLE
Add option to copy as non-escaped string path

### ISSUE THREAD

**Issue by chenasraf** [nidu/vscode-copy-json-path#6]
I mainly use this extension for copying JSON dot-notation paths from locale json file to JS - usually these are used inside a string in a function, a-la:

    // JSON
    "globals": {
        "ok-label": "OK",
        "cancel": "Cancel"
    }

---

    // Usage:
    t('globals.ok-label', 'OK')

Currently, the extension copies paths with invalid chars (specifically `-` in my case) and wraps these segments in `["` and `"]` (e.g. copying "ok-label" from the above JSON would copy `globals["ok-label"]`.

It would be really cool to have some option to change this so the escaping isn't done automatically - I would like to copy `globals.ok-label` instead.

Thanks for a great extension!

**Comment by nidu** [comment]
Glad someone uses it!

Sounds good to me, but what characters do we allow then in addition to `-`? What is the tool you're using that allows paths like this?

I could add a command like "Copy Json Path (no brackets)"

**Comment by chenasraf** [comment]
We're using `i18next`, which lets you have any arbitrary JSON structure with any strings for keys. We decided to use kebab-case to allow an easier keyboard navigation between words inside the same segment (separated by `.`).

I'm not sure if an additional command would be the best way to approach this, I'd expect a `settings.json` change to toggle this on/off with a boolean (which lets it be changed either on the user level or project level), though I wouldn't be against this option, if it's easier to get done.

**Comment by nidu** [comment]
@chenasraf I'm really sorry, I completely lost track of it. Is this one still relevant to you?

**Comment by chenasraf** [comment]
@nidu Sure, I still use the extension.

**Comment by nidu** [comment]
@chenasraf what about having a regex setting that is used to define whether key should be quoted or not?
If regex matches - key is not quoted, so if you want to add `-` - you just add a dash to the regex. This way you can support arbitrary keys. No new command required.

![image](https://user-images.githubusercontent.com/434377/114077409-0f169d00-98a8-11eb-944b-078bc229e4fe.png)

**Comment by chenasraf** [comment]
Sure, sounds great :D

**Comment by nidu** [comment]
@chenasraf one thing - indices are handled differently currently. I think it would be pretty obscure usage but do you need also e.g. `a.1.b` instead of `a[1].b`? In this case we'll have to add some other flag for indices

**Comment by chenasraf** [comment]
Hmm... For my use case numbered indices are fine this way, I think. Don't know about the generalized. But I think either way this is better than before so might as well start without it if it's extra work

**Comment by nidu** [comment]
@chenasraf published as version 0.2.0. Please take a look and reopen the issue if anything goes wrong!
